#!/bin/bash

set -eof pipefail

cat <<EOF
	1.Show tags, create and delete tag (local and remote
	2.Show commit between 2 tags
	3.exit
EOF

read -p "Choose the option > " opt
	if [ -z "$opt" ]; then
		return
	fi
case $opt in
	1)
		echo "Showing tags"
			git tag
			read -p "Do you want to create or delete tags? Choose R|r to delete remote tag [y/n/r]" opt2
		case $opt2 in
			Y|y)
			
		read -p "Create or delete tag or exit [c/d/e] " answ
			if [[ "$answ" == "c" ]] || [[ "$answ" == "C" ]]; then
					read -p "Put the message > " mes
				git tag -a v1.0 -m "$mes"
			elif [[ "$answ" == "d" ]] || [[ "$answ" == "D" ]]; then
					read -p "Put the tag for deletion > " del
						read -p "Press enter to continue..."
							git tag -d "$del"
			elif [[ $answ == "e" ]] || [[ "$answ" == "D" ]]; then
						return
			else 
				echo "Error. Empty string."
					exit 1
			fi
					
				;;
			R|r) read -p "Put the name or remote tag > " name
				read -p "Press enter to delete..."
					git push origin refs/tags/$name
				echo "Your $name was deleted" 
					exit 0
				;;
			N|n)
				exit 0
				;;
		esac	
					;;
	2) 
		read -p "Put the old_tag > " tg1
			read -p "Put the new_tag " tg2
				git log $tg1 $tg2						
					exit 0
					;;
	3)
		exit 0
esac
				
