#!/bin/bash

i=$1

if [ -z "$i" ]; then
	echo "Usage $0"
	exit 2
fi

regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'

if [[ $i =~ $regex ]]; then
	echo "Valid"
	exit 0
else
	echo "Invalid"
	exit 1
fi
