#!/bin/bash

i=$1

if [ -z $i ]; then
	echo "Put the .log file"
	exit 2
fi

reg_ip='^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$'
reg_data='^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
reg_http='^[0-9]{3}$'

echo "IP"

grep -oE "$reg_ip" "$i" | sort | uniq -c

echo "DATE"

grep -oE "$reg_data" "$i" | sort | uniq -c

echo "HTTP CODE"

grep -oE "$reg_http" "$i" | sort | uniq -c
