#!/bin/bash

i=$1

if [ -z $i ]; then
	exit 1
fi

reg_mail='^[a-zA-Z0-9._/%+-]+@[a-zA-Z0-9._/%+-]+\.[a-zA-Z0-9._/%+-]$'
reg_phone='^[0-9._/+]$+\s'
reg_url='^[a-z:/]+\.[a-zA-Z0-9-]+\.[a-z]$'
reg_space='^[[:space:]]*$'

echo	"Deleting email adress"

sed "/$reg_mail/d"

echo	"Replace number with [PHONE]"

sed "/$reg_phone/d; a/PHONE"

echo 	"Deleting URLS"

sed "/$reg_url/d"

echo	"Deleting any space"

sed "/$reg_space/d" 
