name: "ISW checker"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Verify Compose format
        run: |
          docker compose -f docker-compose.yml config -q

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          hide-progress: true
          exit-code: '1' 
          severity: 'CRITICAL,HIGH'

